[package]
name = "ctviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
bitflags = "2.9.1"
sdl2 = "0.38.0"
png = "0.17.13"
clap = { version = "4.5.41", features = ["derive"] }

[profile.release]
strip = true
#trim-paths = true
panic = "abort"
